### ISSUE TITLE
UNHANDLED REJECTION: Error: Do not call .start() more than once

### ISSUE THREAD

**Issue by allyusd** [WaBLin123/ah-typeorm-plugin#4]
I use ah-typeorm-plugin with elastic-apm-node.
When actionhero start, I get the error: UNHANDLED REJECTION: Error: Do not call .start() more than once

=== logs
192.168.5.1 @ 2021-04-20T09:40:31.622Z - info: UNHANDLED REJECTION: Error: Do not call .start() more than once
at Agent.start (/app/node_modules/elastic-apm-node/lib/agent.js:126:31)
at /app/node_modules/***/src/config/logger.ts:26:24
at /app/node_modules/ah-typeorm-plugin/node_modules/actionhero/dist/modules/log.js:20:28
at Array.map (<anonymous>)
at Object.<anonymous> (/app/node_modules/ah-typeorm-plugin/node_modules/actionhero/dist/modules/log.js:19:50)
at Module._compile (internal/modules/cjs/loader.js:1015:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
at Module.load (internal/modules/cjs/loader.js:879:32)
at Function.Module._load (internal/modules/cjs/loader.js:724:14)
at Module.require (internal/modules/cjs/loader.js:903:19)
at Module.Hook._require.Module.require (/app/node_modules/require-in-the-middle/index.js:80:39)
at require (internal/modules/cjs/helpers.js:74:18)
at Object.<anonymous> (/app/node_modules/ah-typeorm-plugin/node_modules/actionhero/dist/classes/process.js:8:15)
at Module._compile (internal/modules/cjs/loader.js:1015:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
at Module.load (internal/modules/cjs/loader.js:879:32)
at Function.Module._load (internal/modules/cjs/loader.js:724:14)
at Module.require (internal/modules/cjs/loader.js:903:19)
at Module.Hook._require.Module.require (/app/node_modules/require-in-the-middle/index.js:80:39)
at require (internal/modules/cjs/helpers.js:74:18)
at Object.<anonymous> (/app/node_modules/ah-typeorm-plugin/node_modules/actionhero/dist/index.js:7:17)
at Module._compile (internal/modules/cjs/loader.js:1015:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
at Module.load (internal/modules/cjs/loader.js:879:32)
at Function.Module._load (internal/modules/cjs/loader.js:724:14)
at Module.require (internal/modules/cjs/loader.js:903:19)
at Module.Hook._require.Module.require (/app/node_modules/require-in-the-middle/index.js:80:39)
at require (internal/modules/cjs/helpers.js:74:18)
at Object.<anonymous> (/app/node_modules/ah-typeorm-plugin/src/initializers/typeorm.ts:3:1)
at Module._compile (internal/modules/cjs/loader.js:1015:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
at Module.load (internal/modules/cjs/loader.js:879:32)
at Function.Module._load (internal/modules/cjs/loader.js:724:14)
at Module.require (internal/modules/cjs/loader.js:903:19)
at Module.Hook._require.Module.require (/app/node_modules/require-in-the-middle/index.js:80:39)
at require (internal/modules/cjs/helpers.js:74:18)
at /app/node_modules/actionhero/dist/classes/process.js:70:35
at Array.forEach (<anonymous>)
at Process.initialize (/app/node_modules/actionhero/dist/classes/process.js:65:26)
at Process.start (/app/node_modules/actionhero/dist/classes/process.js:178:24)
at main (/app/dist/server.js:13:15)
192.168.5.1 @ 2021-04-20T09:40:31.627Z - crit: Cannot shut down actionhero, not running

**Comment by allyusd** [comment]
I send PR to fix it
